### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'item'

### ISSUE THREAD

**Issue by wudapeng268** [Leechikara/Incremental-Dialogue-System#1]
Hi Leechikara,

Thanks for your code. When I run the code, I got following error:

```
vocab size: 655
Longest sentence length 11
Longest candidate sentence length 21
Longest story length 22
Average story length 6
/public/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1340: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    agent.main()
  File "/home/wup/Incremental-Dialogue-System/cvae.py", line 305, in main
    self.simulate_run()
  File "/home/wup/Incremental-Dialogue-System/cvae.py", line 355, in simulate_run
    log["loss"].append(loss.item())
AttributeError: 'NoneType' object has no attribute 'item'
```

It may because variable ``loss`` is None when inference.

**Comment by PeterS111** [comment]
Hi Leechikara,

Fantastic paper!
but I have the same problem as wudapeng268 (above) with running the code:

  File "C:\Users\M\IDS\run.py", line 26, in <module>
    agent.main()
  File "C:\Users\M\IDS\cvae.py", line 305, in main
    self.simulate_run()
  File "C:\Users\M\IDS\cvae.py", line 355, in simulate_run
    log["loss"].append(loss.item())
AttributeError: 'NoneType' object has no attribute 'item'

Could you please give more specific advice on how to run the code from scratch?

Thanks!

**Comment by TianboJi** [comment]
Hi Leechikara,

Same here. 

```
Traceback (most recent call last):
  File "/home/jitianbo/working/workspace/Dialogue/IncrementalDialogueSystem/run.py", line 26, in <module>
    agent.main()
  File "/home/jitianbo/working/workspace/Dialogue/IncrementalDialogueSystem/cvae.py", line 305, in main
    self.simulate_run()
  File "/home/jitianbo/working/workspace/Dialogue/IncrementalDialogueSystem/cvae.py", line 355, in simulate_run
    log["loss"].append(loss.item())
AttributeError: 'NoneType' object has no attribute 'item'
```

Could you please help to fix it? Many thanks.

**Comment by PeterS111** [comment]
Hi Everyone,

We managed to fix the bugs in IDS code (for now).

Here it goes:

1.
Replace line 355 in  cvae.py:
log["loss"].append(loss.item())

with:

if loss is not None:
        log["loss"].append(loss.item())        
else:
    log["loss"].append(None)

2.
Replace lines 41 and 42 in config.py:

model_save_path = "checkpoints/task_1_deploy_from_scratch_model.pkl"
debug_path = "debug/task_1_deploy_from_scratch_debug.pkl"

with:

import os
import time

_#Create "./checkpoints" and "./debug" directories if they don't exist_
if not os.path.exists("checkpoints"):
    os.mkdir("checkpoints")
if not os.path.exists("debug"):
    os.mkdir("debug")

_#Add task number and timestring to saved models' filename to allow storing multiple models_
timestr = time.strftime("%Y%m%d-%H%M%S")    
model_save_path = "checkpoints/{task}_deploy_from_scratch_model_{time}.pkl".format(task=coming_task, time=timestr)
debug_path = "debug/{task}_deploy_from_scratch_debug_{time}.pkl".format(task=coming_task, time=timestr)
            
3. 
Many places in code give the following error:

return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1233: character maps to <undefined>

This happens for example in cvae.py line 115:

with open(os.path.join(DATA_ROOT, "candidate", "task_1.txt")) as f:

Fix it by adding "encoding="UTF-8" like this:

with open(os.path.join(DATA_ROOT, "candidate", "task_1.txt"),encoding="UTF-8") as f:

You will have to do it in every place where this error occurs.


Sorry for no indentation.
